### ISSUE TITLE
MCA interface in spec2nexus has changed

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#123]
Since [issue 55](https://github.com/prjemian/spec2nexus/issues/55) was resolved in [spec2nexus](https://github.com/prjemian/spec2nexus), the code in `nexpy.readers.readspec` is raising exceptions when it imports SPEC files with MCA spectra.

```
Traceback (most recent call last):
  File "/path/to/nexpy/gui/importdialog.py", line 48, in accept
    self.mainwindow.import_data()
  File "/path/to/nexpy/gui/mainwindow.py", line 1133, in import_data
    imported_data = self.import_dialog.get_data()
  File "/path/to/nexpy/readers/readspec.py", line 112, in get_data
    return Parser(self.spec).toTree(scans)
  File "/path/to/nexpy/readers/readspec.py", line 185, in toTree
    entry.data = self.scan_NXdata(scan)            # store the scan data
  File "/path/to/nexpy/readers/readspec.py", line 253, in scan_NXdata
    self.parser_1D_columns(nxdata, scan)
  File "/path/to/nexpy/readers/readspec.py", line 274, in parser_1D_columns
    self.parser_mca_spectra(nxdata, scan, axis)
  File "/path/to/nexpy/readers/readspec.py", line 280, in parser_mca_spectra
    nxdata.mca__spectrum_channel = NXfield(range(1, len(scan.data['_mca_'][0])+1))
KeyError: 0
```

**Comment by prjemian** [comment]
This exception trace resulted importing 33id_spec.dat (available in the spec2nexus project).

That SPEC file has one MCA spectrum in a scan, if at all.
With spec2nexus issue 55 noted above, there is a test file with 4 spectra (`mca_spectra_example.dat`).  Use that one to test that the problem is fixed for many spectra.

**Comment by prjemian** [comment]
Yet still a problem importing `33id_spec.dat`.  Here's the new trace:

```
Traceback (most recent call last):
  File "/home/prjemian/Documents/eclipse/nexpy/src/nexpy/gui/importdialog.py", line 48, in accept
    self.mainwindow.import_data()
  File "/home/prjemian/Documents/eclipse/nexpy/src/nexpy/gui/mainwindow.py", line 1133, in import_data
    imported_data = self.import_dialog.get_data()
  File "/home/prjemian/Documents/eclipse/nexpy/src/nexpy/readers/readspec.py", line 112, in get_data
    return Parser(self.spec).toTree(scans)
  File "/home/prjemian/Documents/eclipse/nexpy/src/nexpy/readers/readspec.py", line 185, in toTree
    entry.data = self.scan_NXdata(scan)            # store the scan data
  File "/home/prjemian/Documents/eclipse/nexpy/src/nexpy/readers/readspec.py", line 242, in scan_NXdata
    self.parser_mesh(nxdata, scan)
  File "/home/prjemian/Documents/eclipse/nexpy/src/nexpy/readers/readspec.py", line 348, in parser_mesh
    mca_data = mca_dict[0]
KeyError: 0
```

**Comment by prjemian** [comment]
To allow for more than one MCA, the names of the MCA returned by `readspec()` will change as this issue is resolved.  New names will be simpler: `__mca` when only one MCA is reported, `__mca1`, `__mca2`, ... when more than one MCA is reported.

**Comment by rayosborn** [comment]
Sorry I didn't get around to this quicker, but I will merge this as soon as I have made my own test.
